DML_ROOT =
GBDT_DIR = $(DML_ROOT)/gbdt
INC_DIR = $(GBDT_DIR)/include
COM_DIR = $(GBDT_DIR)/common
MIX_DIR = $(GBDT_DIR)/mixworker
MAS_DIR = $(GBDT_DIR)/master

CFLAGS = '-lpthread '
OPT = '-O3'
CCC = 'mpicxx '


